### ISSUE TITLE
altacastStandalone v1 SC2 Support

### ISSUE THREAD

**Issue by thavincinew** [DustyDrifter/AltaCast#1]
Hi there.

Not really an issue however i would really appreciate help and even more so a resolution!

Is there anyway to get the Standalone version to have support for Shoutcast v2?
Or is there perhaps a newer version?

**Comment by DustyDrifter** [comment]
Hello.
Development has been on hold due to personal issues. SC v2 support is on the short list to be done and as soon as time permits I will update the program. Thanks for your understanding. 

DD
