### ISSUE TITLE
Will not build in VS 2015

### ISSUE THREAD

**Issue by adamburnsuk** [DustyDrifter/AltaCast#10]
I have cloned project and attempted to build in vs 2015 and it will not build.  I'm new to using github and not sure how to contact Dusty, so I'm hoping he will see issue.

Severity    Code    Description Project File    Line    Suppression State
Error   MSB8020 The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".   altacastStandalone  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets   55  

I have been unsuccessful in retargetting as well and can't find a download of VS 2010.

**Comment by DustyDrifter** [comment]
My current development environment is out of date which is why there hasn't been any activity lately. I plan on upgrading everything after January. At that time I intend to redo the solution to modern code and drop the ancient VS 6 code.
