### ISSUE TITLE
Altacast crashes on RDP access

### ISSUE THREAD

**Issue by jellytussle** [DustyDrifter/AltaCast#11]
Hi,
we have been using Oddcast/Edcast/Altacast for many years, having upgraded to Altacast last year.
We have a headless Windows 10 box running both Icecast 2.4.3 and Altacast.
Everything has been working fine until the last couple of months, when we noticed accessing the Altacast box using RDP caused issues. Connecting to it was no problem, but disconnecting RDP caused Altacast to stop working with no error messages. Restarting Altacast fixes it.
Not sure if it is us or a Windows update. We may need to rebuild it, but I thought I'd let you know in case you had seen this.
Thanks,
Dave

**Comment by DustyDrifter** [comment]
I have seen a similar issue on remote dedicated servers. Microsoft likes to disable sound cards on RDP connections. In order for it to remain enabled, a separate "Terminal Services" licence must be purchased. I don't have a Windows 10 box at this time, but I presume that is the issue. Either way, that is something I can't fix.
