### ISSUE TITLE
Have to run as admin every time

### ISSUE THREAD

**Issue by ghost** [DustyDrifter/AltaCast#2]
When installing the latest version of AltaCast from the website, and I install it with a computer with Windows Vista or later I have to run as administrator every time or the program will not save settings and work properly.
This is because it saves the settings in the program files folder, and User Account Control messes with that folder. Could it be made to save the settings in %appdata% folder, or even better be switched into a portable application so it can be moved around?

**Comment by DustyDrifter** [comment]
Permissions in Vista and later is a known issue. 

See here: 
http://www.radiodj.ro/community/index.php?topic=2445.0
