### ISSUE TITLE
Windows 8/Windows 10 support?

### ISSUE THREAD

**Issue by ghost** [DustyDrifter/AltaCast#5]
Hello! As i have found no other contact possibility i am sorry to "spam" gihtub now with my "issue":

Anyway... Does Altacast support Windows 8 or 10? Talking about the stand alone version. If not, is support for both systems planned in the future?

Thanks!

**Comment by DustyDrifter** [comment]
I don't have either of those systems for testing, unfortunately..... :(

**Comment by AndisGrossteins** [comment]
@SJ-Diamond Altacast works on Windows 8 & 10 without any problems. I've tested and it works.

Screenshot with Altacast and Edcast running on Windows 10:
![Screenshot with Altacast and Edcast running on Windows 10](http://i.imgur.com/S4bRLyi.png)

**Comment by DustyDrifter** [comment]
Hi Andy! :)

Thanks for the clarification.
