### ISSUE TITLE
identifier "PLVGROUP" is undefined

### ISSUE THREAD

**Issue by alvaromlg** [DustyDrifter/AltaCast#8]
Hello, I am trying to compile the altacastStandalone project and I am having some afxcmn.h issues.

Do I have to include the commctrl.h header?

Here is the full traceback of one of those errors

Severity    Code    Description Project File    Line    Suppression State Error (active)        identifier "PLVGROUP" is undefined   altacastStandalone c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include\afxcmn.h  556

Thanks in advance!

**Comment by alvaromlg** [comment]
Nevermind, they are IntelliSense errors

**Comment by johnkuriakose12** [comment]
How do i remove this error it does not allow to build the application.
