### ISSUE TITLE
Opus streams not recognized by Icecast YP

### ISSUE THREAD

**Issue by asymcon** [DustyDrifter/AltaCast#9]
Hi there DustyDrifter,
I'm having multiple issues with the Opus encoder built into Altacast for RadioDJ. 
Track name field is not updated (stays blank).
Any Opus stream is not recognized by Icecast's YP. 

When switched to Vorbis, suddenly everything works fine. 
Any idea what might be the cause of these issues?
Thanks

**Comment by DustyDrifter** [comment]
The developers haven't added that capability to opus. Out of my control. Sorry.
 :(
